=== stevkan/bf-composer-samples/v2/CustomerHandoffBot/CustomerHandoffBot/manifests/skill-manifest.json
{
  "$id": "https://schemas.botframework.com/schemas/skills/v2.2/skill-manifest.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$version": "2.2.0",
  "title": "Skill Manifest Schema",
  "description": "A schema for Bot Framework skill manifests",
  "type": "object",
  "required": ["$id", "$schema", "name", "version", "publisherName", "endpoints"],
  "properties": {
    "$schema": {},
    "$id": {},
    "name": {},
    "version": {},
    "description": {},
    "publisherName": {},
    "privacyUrl": {},
    "copyright": {},
    "license": {},
    "iconUrl": {},
    "tags": {},
    "endpoints": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "title": "Skill endpoints",
      "description": "List of endpoints supported by the skill",
      "items": {
        "$ref": "#/definitions/endpoint"
      }
    },
    "dispatchModels": {},
    "activities": {
      "type": "object",
      "title": "Activities",
      "description": "Definition of activities to enable skill host tooling to programmatically interact with the skill.",
      "additionalProperties": {
        "oneOf": [
          {
            "$ref": "#/definitions/eventActivity"
          },
          {
            "$ref": "#/definitions/invokeActivity"
          },
          {
            "$ref": "#/definitions/messageActivity"
          },
          {
            "$ref": "#/definitions/otherActivities"
          }
        ]
      }
    },
    "activitiesSent": {},
    "definitions": {}
  },
  "additionalProperties": false,
  "definitions": {
    "endpoint": {
      "type": "object",
      "title": "Skill endpoint",
      "description": "Skill endpoint definition",
      "required": ["name", "endpointUrl", "msAppId"],
      "properties": {
        "name": {
          "type": "string",
          "title": "Endpoint name",
          "description": "Unique name for the endpoint",
          "default": "default"
        },
        "protocol": {
          "type": "string",
          "title": "Endpoint protocol",
          "description": "Supported protocol",
          "default": "BotFrameworkV3"
        },
        "description": {
          "type": "string",
          "title": "Endpoint description",
          "description": "Description of the endpoint",
          "examples": ["Production bot"]
        },
        "endpointUrl": {
          "type": "string",
          "format": "uri",
          "title": "Endpoint URL",
          "description": "Endpoint for the skill",
          "examples": ["http://contoso.com/api/messaages"]
        },
        "msAppId": {
          "type": "string",
          "title": "Microsoft App Id",
          "pattern": "^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$",
          "description": "The Microsoft AppId for the skill. This app ID is used to authenticate requests"
        }
      },
      "additionalProperties": false
    },
    "eventActivity": {},
    "invokeActivity": {},
    "messageActivity": {},
    "otherActivities": {},
    "languageModel": {}
  }
}

=== stevkan/bf-composer-samples/v2/CQA_Test_Bot/Actual_CQA_Test_Bot/Actual_CQA_Test_Bot/manifests/Actual_CQA_Test_Bot-manifest.json
{
  "$schema": "https://schemas.botframework.com/schemas/skills/v2.2/skill-manifest.json",
  "$id": "Actual_CQA_Test_Bot-f5f72913-e3cb-4a1d-8cfe-e684bf3f944b",
  "endpoints": [],
  "name": "Actual_CQA_Test_Bot",
  "version": "1.0.0",
  "publisherName": "SK",
  "activities": {
    "Actual_CQA_Test_Bot": {
      "type": "event",
      "name": "Actual_CQA_Test_Bot"
    },
    "conversationUpdate": {
      "type": "conversationUpdate"
    }
  }
}

=== stevkan/bf-composer-samples/v2/EnterpriseAssistant/Calendar/manifests/Calendar-manifest.json
{
  "$schema": "https://schemas.botframework.com/schemas/skills/v2.2/skill-manifest.json",
  "$id": "Calendar-1cde87cb-b69c-4049-8b89-c72cb4b2ff0c",
  "endpoints": [
    {
      "protocol": "BotFrameworkV3",
      "name": "CalendarSkill",
      "endpointUrl": "https://EnterpriseCalendarSkill.azurewebsites.net/api/messages",
      "description": "<description>",
      "msAppId": "f928450a-6ead-4377-8954-432bf0a29032"
    }
  ],
  "name": "CalendarSkill",
  "version": "1.0.0",
  "publisherName": "Steven Kanberg",
  "activities": {
    "Calendar": {
      "type": "event",
      "name": "Calendar"
    },
    "AuthenticationDialog": {
      "type": "event",
      "name": "AuthenticationDialog"
    },
    "CancelEventDialog": {
      "type": "event",
      "name": "CancelEventDialog"
    },
    "CreateEventDialog": {
      "type": "event",
      "name": "CreateEventDialog"
    },
    "GetContactsDialog": {
      "type": "event",
      "name": "GetContactsDialog"
    },
    "GetEventsDialog": {
      "type": "event",
      "name": "GetEventsDialog"
    },
    "ListDialog": {
      "type": "event",
      "name": "ListDialog"
    },
    "ResolveDateTimeDialog": {
      "type": "event",
      "name": "ResolveDateTimeDialog"
    },
    "RespondToEventDialog": {
      "type": "event",
      "name": "RespondToEventDialog"
    },
    "ShowEventsDialog": {
      "type": "event",
      "name": "ShowEventsDialog"
    },
    "UpdateEventDialog": {
      "type": "event",
      "name": "UpdateEventDialog"
    },
    "conversationUpdate": {
      "type": "conversationUpdate"
    },
    "message": {
      "type": "message"
    }
  },
  "dispatchModels": {
    "languages": {
      "en-us": [
        {
          "name": "Calendar",
          "contentType": "application/lu",
          "url": "https://EnterpriseCalendarSkill.azurewebsites.net/manifests/skill-Calendar.en-us.lu",
          "description": "<description>"
        }
      ]
    },
    "intents": [
      "Cancel",
      "CancelEvent",
      "CreateEvent",
      "GetAvailabilityBreaks",
      "GetAvailabilityFirst",
      "GetAvailabilityLast",
      "GetEventAttendees",
      "GetEventDateTime",
      "GetEventLocation",
      "GetEvents",
      "Help",
      "LaunchChat",
      "Logout",
      "RespondAccept",
      "RespondDecline",
      "RespondTentativelyAccept",
      "SetAttendeesAdd",
      "SetAttendeesRemove",
      "SetDateTime",
      "SetDescription",
      "SetDuration",
      "SetLocation",
      "SetOnlineMeetingAdd",
      "SetOnlineMeetingRemove",
      "SetTitle",
      "UpdateEvent"
    ]
  }
}

=== stevkan/bf-composer-samples/v2/EnterpriseAssistant/People/manifests/People-manifest.json
{
  "$schema": "https://schemas.botframework.com/schemas/skills/v2.2/skill-manifest.json",
  "$id": "People-94c5a9d2-5adb-4e7b-912c-852757e6bf46",
  "endpoints": [
    {
      "protocol": "BotFrameworkV3",
      "name": "EnterprisePeopleSkill",
      "endpointUrl": "https://EnterprisePeopleSkill.azurewebsites.net/api/messages",
      "description": "<description>",
      "msAppId": "4d85014d-e6a2-4916-b466-1c8ac81a2a16"
    }
  ],
  "name": "PeopleSkill",
  "version": "1.0.0",
  "publisherName": "Steven Kanberg",
  "activities": {
    "People": {
      "type": "event",
      "name": "People"
    },
    "AuthenticationDialog": {
      "type": "event",
      "name": "AuthenticationDialog",
      "description": "Dialog for getting OAuth token to make calls to rest of the services APIs"
    },
    "GetCollaboratorsDialog": {
      "type": "event",
      "name": "GetCollaboratorsDialog"
    },
    "GetDirectReportsDialog": {
      "type": "event",
      "name": "GetDirectReportsDialog"
    },
    "GetManagerDialog": {
      "type": "event",
      "name": "GetManagerDialog"
    },
    "GetPeersDialog": {
      "type": "event",
      "name": "GetPeersDialog"
    },
    "GetProfileDialog": {
      "type": "event",
      "name": "GetProfileDialog"
    },
    "GetUserDialog": {
      "type": "event",
      "name": "GetUserDialog"
    },
    "ListDialog": {
      "type": "event",
      "name": "ListDialog",
      "value": {
        "properties": {
          "templates.icon": {
            "description": "LG template ID for list card icon",
            "$ref": "https://schemas.botframework.com/schemas/component/v1.0/component.schema#/definitions/stringExpression",
            "title": "Templates Icon"
          },
          "templates.title": {
            "description": "LG template ID for list card title",
            "$ref": "https://schemas.botframework.com/schemas/component/v1.0/component.schema#/definitions/stringExpression",
            "title": "Templates Title"
          },
          "templates.item": {
            "description": "LG template ID for list item",
            "$ref": "https://schemas.botframework.com/schemas/component/v1.0/component.schema#/definitions/stringExpression",
            "title": "Templates Item"
          },
          "templates.initialPrompt": {
            "description": "LG template ID for the initial prompt to show with the list card",
            "$ref": "https://schemas.botframework.com/schemas/component/v1.0/component.schema#/definitions/stringExpression",
            "title": "Templates Initial Prompt"
          },
          "templates.showMorePrompt": {
            "description": "LG template ID for the prompt to show when user navigates to see more results",
            "$ref": "https://schemas.botframework.com/schemas/component/v1.0/component.schema#/definitions/stringExpression",
            "title": "Templates Show More Prompt"
          },
          "templates.skipResponse": {
            "description": "LG template ID for the response when a user skips selecting an option",
            "$ref": "https://schemas.botframework.com/schemas/component/v1.0/component.schema#/definitions/stringExpression",
            "title": "Templates Skip Response"
          },
          "templates.defaultValueResponse": {
            "description": "LG template ID for the response when the default choice is selected",
            "$ref": "https://schemas.botframework.com/schemas/component/v1.0/component.schema#/definitions/stringExpression",
            "title": "Templates Default Value Response"
          },
          "templates.noItemsResponse": {
            "description": "LG template ID for response when no items are found for the list card",
            "$ref": "https://schemas.botframework.com/schemas/component/v1.0/component.schema#/definitions/stringExpression",
            "title": "Templates No Items Response"
          },
          "actionTitleProperty": {
            "description": "Property of the list item object to use for the action title of the choice objects.",
            "$ref": "https://schemas.botframework.com/schemas/component/v1.0/component.schema#/definitions/stringExpression",
            "title": "Action Title Property"
          },
          "getItemsEvent": {
            "description": "ID for dialog event on calling dialog to populate list items",
            "$ref": "https://schemas.botframework.com/schemas/component/v1.0/component.schema#/definitions/stringExpression",
            "title": "Get Items Event"
          },
          "itemsProperty": {
            "description": "Named state property where list items are stored.",
            "$ref": "https://schemas.botframework.com/schemas/component/v1.0/component.schema#/definitions/stringExpression",
            "title": "Items Property"
          },
          "doSelection": {
            "description": "Boolean property indicating whether the list will require the user to select a choice",
            "title": "Do Selection",
            "$ref": "https://schemas.botframework.com/schemas/component/v1.0/component.schema#/definitions/booleanExpression"
          },
          "additionalOptions": {
            "description": "Object property with custom properties used for LG responses",
            "title": "Additional Options",
            "$ref": "https://schemas.botframework.com/schemas/component/v1.0/component.schema#/definitions/objectExpression"
          }
        },
        "type": "object"
      }
    },
    "conversationUpdate": {
      "type": "conversationUpdate"
    },
    "message": {
      "type": "message"
    }
  },
  "dispatchModels": {
    "languages": {
      "en-us": [
        {
          "name": "People",
          "contentType": "application/lu",
          "url": "https://EnterprisePeopleSkill.azurewebsites.net/manifests/skill-People.en-us.lu",
          "description": "<description>"
        }
      ]
    },
    "intents": [
      "GetCollaborators",
      "GetDepartment",
      "GetDirectReports",
      "GetEmailAddress",
      "GetJobTitle",
      "GetLocation",
      "GetManager",
      "GetPeers",
      "GetPhoneNumber",
      "GetProfile",
      "LaunchChat",
      "Logout"
    ]
  }
}

=== stevkan/bf-composer-samples/v1/TestEchoSkill/manifests/TestEchoSkill-2-1-manifest.json
{
  "$schema": "https://schemas.botframework.com/schemas/skills/v2.1/skill-manifest.json",
  "$id": "TestEchoSkill-323c0ff3-5d74-4be9-b4bb-c513ba438499",
  "endpoints": [
    {
      "protocol": "BotFrameworkV3",
      "name": "botberg",
      "endpointUrl": "https://skanberg.ngrok.io/api/messages",
      "msAppId": "613ed145-a6da-4412-9435-30ac5325c84e"
    }
  ],
  "name": "botberg",
  "version": "1.0",
  "publisherName": "SLK",
  "activities": {
    "botberg": {
      "type": "event",
      "name": "botberg"
    },
    "addtodo": {
      "type": "event",
      "name": "addtodo"
    },
    "cleartodos": {
      "type": "event",
      "name": "cleartodos"
    },
    "deletetodo": {
      "type": "event",
      "name": "deletetodo"
    },
    "showtodos": {
      "type": "event",
      "name": "showtodos"
    },
    "conversationUpdate": {
      "type": "conversationUpdate"
    },
    "message": {
      "type": "message"
    }
  },
  "dispatchModels": {
    "intents": [
      "AddIntent",
      "CancelIntent",
      "ClearIntent",
      "DeleteIntent",
      "HelpIntent",
      "ShowIntent"
    ]
  }
}

=== stevkan/bf-composer-samples/v2/CustomerHandoffBot/CustomerHandoffBot/manifests/CustomerHandoffBot-manifest.json
{
  "$schema": "https://schemas.botframework.com/schemas/skills/v2.2/skill-manifest.json",
  "$id": "CustomerHandoffBot-28f5e6d6-fedc-4d8b-8aaf-770f4f92e905",
  "endpoints": [],
  "name": "CustomerHandoffBot",
  "version": "1",
  "publisherName": "CustomHandoffBot",
  "activities": {
    "CustomerHandoffBot": {
      "type": "event",
      "name": "CustomerHandoffBot"
    }
  }
}

=== stevkan/bf-composer-samples/v2/Empty_Bot_0/Empty_Bot_0/manifests/Empty_Bot_0-manifest.json
{
  "$schema": "https://schemas.botframework.com/schemas/skills/v2.2/skill-manifest.json",
  "$id": "Empty_Bot_0-c91756de-618e-4ffa-9a6b-59c804878d2c",
  "endpoints": [
    {
      "protocol": "BotFrameworkV3",
      "name": "v-stkan-empty-bot",
      "endpointUrl": "https://v-stkan-empty-bot.azurewebsites.net/api/messages",
      "description": "<description>",
      "msAppId": "11c16026-da83-4803-9f1d-32e7fbd1e33d"
    }
  ],
  "name": "Empty_Bot_0",
  "version": "41.9",
  "publisherName": "Steven Kanberg",
  "activities": {
    "Empty_Bot_0": {
      "type": "event",
      "name": "Empty_Bot_0"
    },
    "AttachmentDialog": {
      "type": "event",
      "name": "AttachmentDialog"
    },
    "Switch_Dialog": {
      "type": "event",
      "name": "Switch_Dialog"
    },
    "conversationUpdate": {
      "type": "conversationUpdate"
    },
    "message": {
      "type": "message"
    },
    "typing": {
      "type": "typing"
    }
  },
  "dispatchModels": {
    "languages": {
      "en-us": [
        {
          "name": "Empty_Bot_0",
          "contentType": "application/lu",
          "url": "https://v-stkan-empty-bot.azurewebsites.net/manifests/skill-Empty_Bot_0.en-us.lu",
          "description": "<description>"
        }
      ]
    },
    "intents": [
      "AskForAttachment",
      "Switch_trigger"
    ]
  }
}

=== stevkan/bf-composer-samples/v1/TodoSample-0/manifests/TodoSample-0-3-1-manifest.json
{
  "$schema": "https://schemas.botframework.com/schemas/skills/skill-manifest-2.1.preview-1.json",
  "$id": "TodoSample-0-8ed9bfd8-6a4b-4f99-bd24-5eece99e07a3",
  "endpoints": [
    {
      "protocol": "BotFrameworkV3",
      "name": "ToDoSample-endpoint",
      "endpointUrl": "https://fdbbba20fbf6.ngrok.io/api/messages",
      "msAppId": "cd76d309-5c3d-4c58-9b58-abfa7798eba8"
    }
  ],
  "name": "TodoSample-0-manifest",
  "version": "1.0",
  "publisherName": "SLK",
  "activities": {
    "TodoSample-0": {
      "type": "event",
      "name": "TodoSample-0"
    },
    "addtodo": {
      "type": "event",
      "name": "addtodo"
    },
    "cleartodos": {
      "type": "event",
      "name": "cleartodos"
    },
    "deletetodo": {
      "type": "event",
      "name": "deletetodo"
    },
    "showtodos": {
      "type": "event",
      "name": "showtodos"
    },
    "conversationUpdate": {
      "type": "conversationUpdate"
    },
    "message": {
      "type": "message"
    }
  },
  "dispatchModels": {
    "intents": [
      "AddIntent",
      "CancelIntent",
      "ClearIntent",
      "DeleteIntent",
      "HelpIntent",
      "ShowIntent"
    ]
  }
}
